sudo: required
dist: trusty

language: php

php:
   - '7.1'

addons:
  chrome: stable

install:
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

services:
  - mysql
  
before_script:
  - mysql -u root -e 'CREATE DATABASE classifiedz;'
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit --debug
  - php artisan dusk
